server:
  port: 80

spring:
  application:
    name: cloud-consumer=order

  cloud:
    consul:
      host: 192.168.0.101
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 192.168.0.103